name: Bug Report
description: File a bug report.
labels: ['bug']
projects: ['FChat-Horizon/Horizon']
type: bug
body:
  - type: markdown
    id: description
    attributes:
      label: Describe the bug
      description: Please provide a clear and concise description of what the bug is.
  - type: textarea
    id: version-info
    attributes:
      label: Version Information
      placeholder: In the app menu, go to Horizon > About Horizon, click \"Copy Version Info\" and paste it here.
    validations:
      required: true
  - type: markdown
    id: reproduction-steps
    attributes:
      label: To reproduce
      description: Steps to reproduce the behavior. Remember, the more descriptive you are, the easier it is for us to fix the issue!
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
