name: Documentation
description: For the Wiki, documentation or the website.
body:
  - type: textarea
    id: pages
    attributes:
      label: Relevant page(s)
      description: Please link the page(s) the problem occurs in.
    validations:
      required: true
  - type: textarea
    id: browser-info
    attributes:
      label: Browser Information
      description: If it's a problem with the website, please provide the browser(s) and version(s) you are using. Pro-tip! Go to https://www.whatismybrowser.com/ and copy the info shown there.
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the documentation issue here.
